stages:
  - docker
  - cache
  - test
  - deploy

variables:
  REGISTRY: registry.gitlab.com
  IMAGE: $REGISTRY/taig-github/flog
  DOCKER_DRIVER: overlay2
  SBT: sbt -v -sbt-launch-dir ./cache/launchers -Dsbt.global.base=./cache/sbt -Dsbt.boot.directory=./cache/boot -Dsbt.ivy.home=./cache/ivy -Dsbt.coursier.home=./cache/coursier -Dmode=ci

cache: &cache
  key: global
  paths:
    - ./cache/
    - ./**/target/
  policy: pull

docker:
  stage: docker
  image: docker
  services:
    - docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker pull $IMAGE:latest || true
    - docker build --cache-from $IMAGE:latest --tag $IMAGE:latest .
    - docker push $IMAGE:latest

dependencies:
  stage: cache
  image: $IMAGE:latest
  script: $SBT +test:compile
  cache:
    <<: *cache
    policy: pull-push

formatting:
  stage: test
  image: $IMAGE:latest
  script: $SBT scalafmtCheckAll

unit tests:
  stage: test
  image: $IMAGE:latest
  script: $SBT +test

artifacts:
  stage: deploy
  image: $IMAGE:latest
  script: $SBT publishAndRelease
  only:
    - main
    - tags